import { test } from 'node:test';
import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { WebContents } from 'electron';
import type { BrowserTab } from '../src/shared';
import { Certificates } from '../src/main/certificates';

test('TLS decisions bind endpoint, leaf, error and session, with single-use pending answers', t => {
  const directory = mkdtempSync(join(tmpdir(), 'bartizan-certificates-'));
  const certificate = (name: string) => {
    const path = join(directory, name);
    execFileSync('openssl', ['req', '-x509', '-newkey', 'ed25519', '-nodes', '-keyout', path + '.key', '-out', path, '-days', '1', '-subj', '/CN=example.invalid'], { stdio: 'ignore' });
    return { data: readFileSync(path, 'utf8') };
  };
  const muted = new Set<string>();
  const policy = new Certificates(() => {}, muted);
  t.after(() => { policy.close(); rmSync(directory, { recursive: true, force: true }); });
  const a = certificate('a'), b = certificate('b');
  const tab: BrowserTab = { id: 'tab', title: '', url: '', loading: true, canBack: false, canForward: false, audible: false, muted: false, zoom: 100, devtools: false };
  const contents = new EventEmitter();
  policy.attach(tab, contents as WebContents);
  contents.emit('did-start-navigation', { isMainFrame: true, isSameDocument: false, url: 'https://example.invalid/#fragment' });
  const error = 'net::ERR_CERT_AUTHORITY_INVALID';
  const request = (url = 'https://example.invalid/', cert = a, failure = error, main = true) => {
    const results: boolean[] = []; let prevented = false;
    contents.emit('certificate-error', { preventDefault() { prevented = true; } }, url, failure, cert, (allow: boolean) => results.push(allow), main);
    assert.equal(prevented, true); return results;
  };
  assert.deepEqual(request(undefined, undefined, undefined, false), [false]);
  const pending = request();
  assert.deepEqual(pending, []);
  const id = tab.certificate!.id;
  assert.equal(policy.answer(id, true), true);
  assert.deepEqual(pending, [true]);
  assert.equal(policy.answer(id, true), false);
  assert.deepEqual(request('https://example.invalid:443/other', a, error, false), [true]);
  assert.deepEqual(request('wss://example.invalid/socket', a, error, false), [true]);
  assert.deepEqual(request('https://example.invalid:444/', a, error, false), [false]);
  assert.deepEqual(request('https://other.invalid/', a, error, false), [false]);
  assert.deepEqual(request(undefined, b, error, false), [false]);
  assert.deepEqual(request(undefined, a, 'net::ERR_CERT_DATE_INVALID', false), [false]);
  assert.deepEqual(request(undefined, a, 'net::ERR_CERT_REVOKED'), [false]);
  assert.deepEqual(request(undefined, { data: 'invalid' }), [false]);
  const replaced = request(undefined, b);
  const canceled = tab.certificate!.id;
  policy.answer(canceled, false);
  assert.deepEqual(replaced, [false]);
  assert.deepEqual(request(undefined, b), [false]);
  muted.delete(tab.id);
  const navigating = request(undefined, b);
  const stale = tab.certificate!.id;
  contents.emit('did-start-navigation', { isMainFrame: true, isSameDocument: false, url: 'https://new.invalid/' });
  assert.deepEqual(navigating, [false]);
  assert.equal(policy.answer(stale, true), false);
  assert.deepEqual(request(undefined, b), [false]);
  muted.delete(tab.id);
  contents.emit('did-start-navigation', { isMainFrame: true, isSameDocument: false, url: 'https://example.invalid/' });
  const stopped = request(undefined, b);
  contents.emit('did-fail-provisional-load', {}, -3, '', 'https://example.invalid/', true);
  assert.deepEqual(stopped, [false]);
  muted.delete(tab.id);
  const closing = request(undefined, b);
  policy.close();
  assert.deepEqual(closing, [false]);
  assert.deepEqual(request(), [false]);
  const fresh = new Certificates(() => {}, new Set()), other = new EventEmitter();
  const otherTab = { ...tab, id: 'other' };
  fresh.attach(otherTab, other as WebContents);
  const unapproved: boolean[] = [];
  other.emit('certificate-error', { preventDefault() {} }, 'https://example.invalid/', error, a, (allow: boolean) => unapproved.push(allow), false);
  assert.deepEqual(unapproved, [false]); fresh.close();
});
