import { contextBridge, ipcRenderer } from 'electron';
import type { API, Event } from '../shared';
const api: API = {
  graphics: event => ipcRenderer.send('graphics', event),
  reportError: input => ipcRenderer.invoke('report-error', input),
  clearErrors: () => ipcRenderer.invoke('clear-errors'),
  answerCertificate: (id, allow) => ipcRenderer.invoke('certificate-answer', id, allow),
  profileDraft: id => ipcRenderer.invoke('profile-draft', id),
  profilePreview: input => ipcRenderer.invoke('profile-preview', input),
  profileConnect: input => ipcRenderer.invoke('profile-connect', input),
  profileSave: input => ipcRenderer.invoke('profile-save', input),
  reloadConfig: () => ipcRenderer.invoke('reload-config'),
  chooseFile: () => ipcRenderer.invoke('choose-file'),
  settings: patch => ipcRenderer.invoke('settings', patch),
  details: id => ipcRenderer.invoke('details', id),
  connect: target => ipcRenderer.invoke('connect', target),
  disconnect: id => ipcRenderer.invoke('disconnect', id),
  removeConnection: id => ipcRenderer.invoke('remove-connection', id),
  reconnect: id => ipcRenderer.invoke('reconnect', id),
  newTerminal: id => ipcRenderer.invoke('new-terminal', id),
  closeTerminal: id => ipcRenderer.invoke('close-terminal', id),
  newBrowser: id => ipcRenderer.invoke('new-browser', id),
  newBrowserTab: (id, session) => ipcRenderer.invoke('new-browser-tab', id, session),
  renameBrowser: (id, name) => ipcRenderer.invoke('rename-browser', id, name),
  openLink: (id, url, session) => ipcRenderer.invoke('open-link', id, url, session),
  linkMenu: (id, url, session) => ipcRenderer.invoke('link-menu', id, url, session),
  copy: text => ipcRenderer.invoke('copy', text),
  menu: (items, x, y) => ipcRenderer.send('menu', items, x, y),
  input: (id, data) => ipcRenderer.send('input', id, data),
  resize: (id, cols, rows, repaint) => ipcRenderer.send('resize', id, cols, rows, repaint),
  answer: (id, value) => ipcRenderer.invoke('answer', id, value),
  browser: (id, action, tab, url) => ipcRenderer.invoke('browser', id, action, tab, url),
  showBrowser: (id, bounds) => ipcRenderer.send('show-browser', id, bounds),
  onEvent: callback => { const listener = (_: unknown, event: Event) => callback(event); ipcRenderer.on('event', listener); return () => ipcRenderer.removeListener('event', listener); },
};
contextBridge.exposeInMainWorld('bartizan', api);
