import { expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { withDirectory, launch } from './lib/harness.mjs';

await withDirectory('errors', async (directory, cleanup) => {
  const config = join(directory, 'config.yaml');
  await writeFile(config, 'version: [\n');
  const app = await launch(directory, config);
  cleanup(app.close);
  const { application, page, api, errors } = app;
  // The error panel draws in the modal overlay, which a reload replaces.
  let dialogs = await app.modal();
  const button = () => page.getByRole('button', { name: 'Errors', exact: true });
  const panel = () => dialogs.locator('dialog.error-panel');
  const clearHistory = () => panel().getByRole('button', { name: 'Clear History', exact: true });
  const toasts = () => page.locator('[data-sonner-toast][data-removed="false"]');
  const dismiss = toast => toast.getByRole('button', { name: 'Dismiss', exact: true });
  const current = () => dialogs.locator('.error-current');
  const history = () => dialogs.locator('.error-history');
  const report = async (message, connectionId) => {
    await api('reportError', { source: 'rig', message, connectionId, label: connectionId ? 'Fixture' : 'App' });
    await page.clock.runFor(50);
  };

  await expect(page.locator('.rail-actions').getByRole('button', { name: 'Errors', exact: true })).toBeVisible();
  const errorBounds = await button().boundingBox();
  const homeBounds = await page.locator('.home-view').boundingBox();
  assert.ok(errorBounds.x + errorBounds.width <= homeBounds.x, 'Errors sits on the rail beside the home page');
  await expect(page.locator('#error-count')).toHaveText('1');
  await button().click();
  await expect(panel()).toHaveJSProperty('open', true);
  await expect(panel()).toBeFocused();
  await dialogs.keyboard.press('Tab');
  await expect(dialogs.getByRole('combobox', { name: 'Filter', exact: true })).toBeFocused();
  await expect(current()).toContainText('Invalid YAML');
  const activeClass = await button().getAttribute('class');
  await dialogs.keyboard.press('Escape');
  assert.equal(await button().getAttribute('class'), activeClass);
  await button().click();
  await clearHistory().click();
  await expect(current()).toContainText('Invalid YAML');
  await expect(page.locator('#error-count')).toHaveText('1');
  await dialogs.keyboard.press('Escape');
  await writeFile(config, 'version: 1\n');
  await api('reloadConfig');
  await expect(page.locator('#error-count')).toBeHidden();
  await button().click();
  await expect(current()).toBeHidden();
  await expect(clearHistory()).toBeDisabled();
  await expect(dialogs.locator('.error-empty')).toHaveText('No Errors');
  await expect(dialogs.locator('.error-empty')).toBeVisible();
  await dialogs.keyboard.press('Escape');
  await expect(button()).toBeFocused();
  console.log('A configuration error stays current through Clear History until the configuration is fixed.');

  await page.clock.install();
  await report('failure one', 'fixture-a');
  await report('failure two');
  await report('failure three');
  await expect(toasts()).toHaveCount(3);
  await expect(page.locator('[data-sonner-toaster]')).toHaveAttribute('data-y-position', 'bottom');
  // With no connection in view there is no panel; toasts stand where it would, beside the rail.
  const railBounds = await page.locator('.rail').boundingBox();
  const toastBounds = await toasts().first().boundingBox();
  assert.ok(toastBounds.x >= railBounds.x + railBounds.width && toastBounds.x + toastBounds.width <= railBounds.x + railBounds.width + await page.evaluate(() => parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--panel-width'))), 'Toasts stay in the panel\'s column');
  await toasts().first().hover();
  await page.clock.runFor(7000);
  await expect(toasts()).toHaveCount(3);
  await report('failure four');
  await expect(toasts()).toHaveCount(3);
  await expect(toasts().filter({ hasText: 'failure one' })).toHaveCount(0);
  await expect(page.locator('[data-sonner-toaster]')).toContainText('failure four');
  await page.clock.runFor(7000);
  await expect(toasts()).toHaveCount(3);
  await page.mouse.move(600, 300);
  await page.clock.runFor(6500);
  await expect(toasts()).toHaveCount(0);
  console.log('At most three toasts show, the oldest gives way, and hovering pauses their expiry.');

  await report('focused oldest');
  await report('focused middle');
  await report('focused newest');
  await dismiss(toasts().filter({ hasText: 'focused oldest' })).focus();
  await report('focused replacement');
  await page.clock.runFor(400);
  assert.equal(await page.evaluate(() => document.activeElement === document.body), false, 'Evicting the focused toast moves focus to a live control');
  await button().focus();
  await page.clock.runFor(6500);
  await expect(toasts()).toHaveCount(0);

  await report('a long diagnostic '.repeat(200));
  assert.ok((await toasts().boundingBox()).height < 250, 'A long diagnostic stays bounded');
  await expect(toasts().locator('[data-description]')).toHaveCSS('overflow-y', 'auto');
  await dismiss(toasts()).click();
  await page.clock.runFor(400);
  await expect(toasts()).toHaveCount(0);

  await report('repeated failure');
  await report('repeated failure');
  await expect(toasts()).toHaveCount(1);
  await expect(toasts()).toContainText('×2');
  await dismiss(toasts()).click();
  await expect(toasts()).toHaveCount(0);
  await report('repeated failure');
  await page.clock.runFor(400);
  await expect(toasts()).toHaveCount(1);
  await expect(toasts()).toContainText('×3');
  await dismiss(toasts()).click();
  await page.clock.runFor(400);
  console.log('Focus leaves an evicted toast for a live control, long diagnostics stay bounded, and repeats are counted in one toast.');

  await button().click();
  await expect(history()).toContainText('failure one');
  await expect(history()).toContainText('Fixture');
  await expect(history()).toContainText('repeated failure');
  await dialogs.getByRole('combobox', { name: 'Filter', exact: true }).selectOption({ label: 'Fixture' });
  await expect(history()).toContainText('failure one');
  await expect(history()).not.toContainText('failure two');
  await dialogs.keyboard.press('Escape');
  await page.reload();
  dialogs = await app.modal();
  await expect(button()).toBeVisible();
  await expect(toasts()).toHaveCount(0);
  await button().click();
  await expect(history()).toContainText('failure one');
  await expect(history()).toContainText('repeated failure');
  await clearHistory().click();
  await expect(history()).toBeHidden();
  await expect(clearHistory()).toBeDisabled();
  await dialogs.keyboard.press('Escape');
  await application.evaluate(({ BrowserWindow }) => {
    const time = Date.now();
    BrowserWindow.getAllWindows()[0].webContents.send('event', { type: 'errors', log: { current: [], history: [{ id: 100000, kind: 'current', source: 'config', label: 'App', message: 'Recovered within one update', time, lastTime: time, resolvedAt: time, count: 1 }] } });
  });
  await button().click();
  await expect(history()).toContainText('Recovered within one update');
  await expect(toasts()).toHaveCount(0);
  assert.deepEqual(errors, []);
  console.log('History survives a reload, filters by connection and clears; a problem resolved before it arrived shows in history only.');
});
