import { expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { withDirectory, startSshd, sshProfile, launch } from './lib/harness.mjs';

await withDirectory('reconnect', async (directory, cleanup) => {
  const sshd = await startSshd(directory, { config: 'ForceCommand /bin/sh\n' });
  cleanup(sshd.stop);
  const config = join(directory, 'config.yaml');
  await writeFile(config, `version: 1\nsettings:\n  remoteSessionIntegration: false\nprofiles:\n  rig:\n${sshProfile(sshd)}  second:\n${sshProfile(sshd)}  third:\n${sshProfile(sshd)}`);
  const app = await launch(directory, config);
  cleanup(app.close);
  const { page, api, waitState, recordOutput, output, errors } = app;
  await recordOutput();
  const id = await api('connect', { profileId: 'rig' });
  const first = (await waitState(s => s.terminals[0]?.status === 'connected')).terminals[0].id;
  await app.chooseConnection(id);
  const terminal = id => page.locator(`.nav-item[data-kind="terminal"][data-id="${id}"]`);
  await terminal(first).click();
  await api('input', first, "printf 'KEEP_%s\\n' HISTORY\n");
  await expect.poll(() => output(first)).toContain('KEEP_HISTORY');
  await expect(page.locator('.terminal-surface:not([hidden]) .xterm-rows')).toContainText('KEEP_HISTORY');
  const surface = await page.locator('.terminal-surface:not([hidden])').elementHandle();
  await api('input', first, "printf '\\033[?1000h\\033[?1006h'\n");
  await expect.poll(() => output(first)).toContain('\x1b[?1006h');
  const exited = await api('newTerminal', id);
  await api('input', exited, 'exit 0\n');
  await waitState(s => s.terminals.find(t => t.id === exited)?.status === 'closed');
  const ambiguous = await api('newTerminal', id);
  await api('input', ambiguous, 'exit 255\n');
  await waitState(s => s.terminals.find(t => t.id === ambiguous)?.status === 'closed');
  await api('disconnect', id);
  await api('reconnect', id);
  const restored = await waitState(s => s.terminals.find(t => t.id === first)?.status === 'connected');
  assert.equal(restored.terminals.length, 3);
  assert.equal(restored.terminals.find(t => t.id === exited).status, 'closed');
  assert.equal(restored.terminals.find(t => t.id === ambiguous).status, 'closed');
  assert.equal(await surface.evaluate(node => node === document.querySelector('.terminal-surface:not([hidden])')), true);
  await page.locator('.terminal-surface:not([hidden])').hover();
  await page.mouse.wheel(0, -10000);
  await expect(page.locator('.terminal-surface:not([hidden]) .xterm-rows')).toContainText('KEEP_HISTORY');
  await terminal(first).click();
  await page.locator('.terminal-surface:not([hidden])').click({ position: { x: 100, y: 100 } });
  await api('input', first, "printf 'RESTORED_%s\\n' SHELL\n");
  await expect.poll(() => output(first)).toContain('RESTORED_SHELL');
  assert.ok(!(await output(first)).includes('command not found'), 'The new shell must not inherit mouse reporting');
  await terminal(exited).click();
  await page.getByRole('button', { name: 'Reconnect Terminal', exact: true }).click();
  await waitState(s => s.terminals.find(t => t.id === exited)?.status === 'connected');
  await api('input', exited, 'exit 7\n');
  await waitState(s => s.terminals.find(t => t.id === exited)?.status === 'closed');
  await expect.poll(() => output(exited)).toContain('Terminal exited with code 7');
  await api('reconnectTerminal', exited);
  await waitState(s => s.terminals.find(t => t.id === exited)?.status === 'connected');
  await api('disconnect', id);
  await api('reconnect', id);
  await waitState(s => s.terminals.find(t => t.id === exited)?.status === 'connected');
  assert.equal((await app.state()).terminals.find(t => t.id === ambiguous).status, 'closed');
  console.log('Connection reconnect restores interrupted terminals in place; exited and ambiguous terminals require manual retry.');

  // Closing the selected connection follows the displayed order, including the last position.
  const second = await api('connect', { profileId: 'second' });
  const third = await api('connect', { profileId: 'third' });
  await waitState(s => s.connections.every(c => c.status === 'connected'));
  await app.chooseConnection(second);
  await api('disconnect', second);
  await page.locator('.connection-remove:visible').focus();
  await page.keyboard.press('Enter');
  await expect(page.locator(`.connection-chip[data-id="${third}"] .connection-titles`)).toHaveAttribute('aria-current', 'true');
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  assert.equal(await page.locator('.terminal-surface:not([hidden]) textarea').evaluate(node => node === document.activeElement), false);
  await api('disconnect', third);
  await api('removeConnection', third);
  await expect(page.locator(`.connection-chip[data-id="${id}"] .connection-titles`)).toHaveAttribute('aria-current', 'true');
  await api('disconnect', id);
  await api('removeConnection', id);
  await expect(page.locator('.home-button')).toHaveAttribute('aria-current', 'page');
  assert.deepEqual(errors, []);
  console.log('Closing a connection selects its following neighbor, then its preceding neighbor, then Home.');
});
