import { expect } from '@playwright/test';
import assert from 'node:assert/strict';
import * as pty from 'node-pty';
import { execFileSync } from 'node:child_process';
import { writeFile, readFile, mkdir, chmod, unlink } from 'node:fs/promises';
import { join } from 'node:path';
import { userInfo } from 'node:os';
import { parse, stringify } from 'yaml';
import { withDirectory, startSshd, sshProfile, launch } from './lib/harness.mjs';

execFileSync('python3', ['-B', 'tests/remote-helper.py'], { stdio: 'inherit' });

await withDirectory('sessions', async (directory, cleanup) => {
  const bin = join(directory, 'bin'), root = join(directory, `tmux-${userInfo().uid}`), screenRoot = join(directory, 'screen');
  await Promise.all([mkdir(bin), mkdir(root), mkdir(screenRoot, { mode: 0o700 })]);
  const socket = join(root, "socket space ' 雪"), secondSocket = join(root, 'other');
  const pidFile = join(directory, 'helper.pid'), failHelper = join(directory, 'helper-fails');
  const executable = async (file, text) => { await writeFile(file, text); await chmod(file, 0o700); };
  await executable(join(bin, 'python3'), `#!/bin/sh\nif [ -f '${failHelper}' ]; then exit 1; fi\nif [ ! -f '${pidFile}' ]; then sleep 16; fi\necho $$ > '${pidFile}'\nexec /usr/bin/python3 "$@"\n`);
  const login = join(directory, 'login');
  await executable(login, '#!/bin/sh\nexec /bin/sh -c "$2"\n');
  const shell = join(directory, 'shell');
  await executable(shell, `#!/bin/sh\nexport PATH='${bin}':/usr/bin:/bin\nexport SHELL='${login}'\nexport TMUX_TMPDIR='${directory}'\nexport SCREENDIR='${screenRoot}'\nexport XDG_CONFIG_HOME='${directory}/config'\nif [ -z "$SSH_ORIGINAL_COMMAND" ]; then exec /bin/sh; fi\nexec /bin/sh -c "$SSH_ORIGINAL_COMMAND"\n`);
  const tmuxAt = (path, ...args) => execFileSync('/usr/bin/tmux', ['-S', path, ...args], { encoding: 'utf8' });
  const tmux = (...args) => tmuxAt(socket, ...args);
  for (const [path, name] of [[socket, 'build'], [secondSocket, 'other-server']]) {
    tmuxAt(path, '-f', '/dev/null', 'new-session', '-d', '-s', name, 'sleep 600');
    cleanup(() => { try { tmuxAt(path, 'kill-server'); } catch {} });
  }
  for (const name of ['scratch', 'busy']) tmux('new-session', '-d', '-s', name, 'sleep 600');
  execFileSync('screen', ['-dmS', 'screen-work', 'sleep', '600'], { env: { ...process.env, SCREENDIR: screenRoot } });
  cleanup(() => { try { execFileSync('screen', ['-S', 'screen-work', '-X', 'quit'], { env: { ...process.env, SCREENDIR: screenRoot } }); } catch {} });
  const otherClient = pty.spawn('/usr/bin/tmux', ['-S', socket, 'attach-session', '-t', 'busy'], { name: 'xterm-256color', cols: 80, rows: 24, env: { ...process.env, TERM: 'xterm-256color' } });
  let detached = false;
  otherClient.onData(() => {}); otherClient.onExit(() => { detached = true; });
  cleanup(() => { if (!detached) otherClient.kill(); });
  await expect.poll(() => tmux('display-message', '-p', '-t', 'busy', '#{session_attached}').trim()).toBe('1');
  const sshd = await startSshd(directory, { config: `ForceCommand ${shell}\n` }); cleanup(sshd.stop);
  const config = join(directory, 'config.yaml');
  await writeFile(config, `version: 1\nprofiles:\n  test:\n${sshProfile(sshd)}  other:\n${sshProfile(sshd)}`);
  const app = await launch(directory, config); cleanup(app.close);
  const { api, page, waitState, chooseConnection, application, errors } = app;
  await application.evaluate(({ Menu }) => { globalThis.rigMenus = []; Menu.prototype.popup = function () { globalThis.rigMenus.push(this); }; });
  await page.evaluate(() => {
    window.snapshotsA = []; window.snapshotsB = [];
    window.bartizan.onHelperMessage('sessions.snapshot', event => window.snapshotsA.push(event));
    window.bartizan.onHelperMessage('sessions.snapshot', event => window.snapshotsB.push(event));
  });
  const id = await api('connect', { profileId: 'test' });
  await expect.poll(async () => (await app.state()).connections[0]?.remoteSessions?.sessions.length, { timeout: 30000 }).toBe(5);
  await waitState(s => s.connections[0].remoteSessions?.sessions.length === 5, 'five socket-discovered sessions');
  await expect.poll(() => page.evaluate(() => window.snapshotsA.length)).toBeGreaterThan(0);
  assert.deepEqual(await page.evaluate(() => window.snapshotsA), await page.evaluate(() => window.snapshotsB));
  const listed = (await app.state()).connections[0].remoteSessions.sessions;
  assert.equal(new Set(listed.map(s => s.key)).size, 5);
  assert.notEqual(listed.find(s => s.label === 'build').source, listed.find(s => s.label === 'other-server').source);
  await chooseConnection(id);
  const tab = () => page.locator('.nav-item[data-kind="remote"]');
  for (const theme of ['tabs', 'console', 'rail']) { await api('settings', { theme }); await tab().click(); await expect(page.locator('.remote-sessions')).toBeVisible(); }
  await expect(page.locator('.remote-entry + .details-entry')).toBeVisible();
  await page.locator('.nav-item[data-kind="details"]').click();
  await expect(page.locator('.process-row').filter({ hasText: 'Bartizan Helper' }).locator('.process-status')).toHaveText('Running');
  await tab().click();
  const rows = page.locator('.remote-row');
  const row = name => rows.filter({ has: page.getByText(name, { exact: true }) });
  const item = name => row(name).locator('.remote-item');
  await expect(rows).toHaveCount(5);
  await expect(row('busy')).toHaveAttribute('data-standing', 'attached');
  await expect(item('build').locator('.item-detail')).toContainText('1 window');

  // Refresh throttles only its button. Both message subscribers still receive its snapshot.
  const helperPid = Number(await readFile(pidFile, 'utf8'));
  process.kill(helperPid, 'SIGSTOP'); cleanup(() => { try { process.kill(helperPid, 'SIGCONT'); } catch {} });
  await page.waitForTimeout(150);
  const refresh = page.getByRole('button', { name: 'Refresh', exact: true });
  await refresh.click(); await expect(refresh).toBeDisabled();
  await expect(item('build')).not.toHaveAttribute('aria-disabled', 'true');
  await item('build').click();
  await waitState(s => s.terminals.some(t => t.remoteSession?.label === 'build'), 'session opens during refresh');
  process.kill(helperPid, 'SIGCONT'); await tab().click(); await expect(refresh).toBeEnabled();
  await page.getByRole('button', { name: 'Resume All', exact: true }).click();
  await waitState(s => s.terminals.filter(t => t.remoteSession).length === 4, 'detached sessions resumed');
  await tab().click(); await item('busy').click();
  await expect.poll(() => detached).toBe(true);
  await waitState(s => s.terminals.filter(t => t.remoteSession).length === 5, 'busy session taken over');
  assert.equal(tmuxAt(secondSocket, 'display-message', '-p', '-t', 'other-server', '#{session_attached}').trim(), '1');
  await tab().click(); await expect(item('build').locator('.remote-action')).toHaveText('Go To');

  // The stream finds additions and removals without a manual refresh.
  tmux('new-session', '-d', '-s', 'automatic', 'sleep 600');
  await waitState(s => s.connections[0].remoteSessions.sessions.some(x => x.label === 'automatic'), 'automatic session discovery');
  tmux('kill-session', '-t', 'automatic');
  await waitState(s => !s.connections[0].remoteSessions.sessions.some(x => x.label === 'automatic'), 'automatic session removal');
  const temporarySocket = join(root, 'temporary');
  tmuxAt(temporarySocket, '-f', '/dev/null', 'new-session', '-d', '-s', 'temporary', 'sleep 600');
  cleanup(() => { try { tmuxAt(temporarySocket, 'kill-server'); } catch {} });
  tmux('new-session', '-d', '-s', 'outage-stop', 'sleep 600');
  await waitState(s => s.connections[0].remoteSessions.sessions.some(x => x.label === 'temporary'), 'temporary socket discovered');
  const disconnectedSession = (await waitState(s => s.connections[0].remoteSessions.sessions.some(x => x.label === 'outage-stop'), 'session discovered before outage')).connections[0].remoteSessions.sessions.find(s => s.label === 'outage-stop');
  process.kill(helperPid, 'SIGSTOP');
  await refresh.click(); await expect(refresh).toBeDisabled();
  tmuxAt(temporarySocket, 'kill-server');
  process.kill(helperPid, 'SIGKILL');
  await expect(refresh).toBeEnabled();
  // A separate command channel can stop a session while the helper is in backoff.
  await api('killRemoteSession', id, disconnectedSession.key);
  assert.throws(() => tmux('has-session', '-t', 'outage-stop'));
  await expect.poll(async () => Number(await readFile(pidFile, 'utf8'))).not.toBe(helperPid);
  await waitState(s => !s.connections[0].remoteSessions.errors.length && s.connections[0].remoteSessions.sessions.length === 5, 'helper restarts and reconciles vanished sockets');

  const second = await api('connect', { profileId: 'other' });
  await waitState(s => s.connections.find(c => c.id === second)?.remoteSessions?.sessions.length === 5, 'second connection discovers sessions');
  await chooseConnection(second); await tab().click();
  await expect(page.locator('.remote-row[data-standing="open"]')).toHaveCount(0);
  const otherDraft = await api('profileDraft', 'other');
  await api('profileSave', { token: otherDraft.token, values: { remote_sessions: false, terminal: { font_size: 18 } }, reset: [], connect: false });
  await api('settings', { remoteSessionIntegration: false, terminalFontSize: 22 });
  await waitState(s => s.connections.every(c => !c.remoteSessions), 'discovery disabled across connections');
  await api('settings', { remoteSessionIntegration: true });
  await waitState(s => s.connections.find(c => c.id === id)?.remoteSessions?.sessions.length === 5, 'inherited discovery starts');
  assert.equal((await app.state()).connections.find(c => c.id === second).remoteSessions, undefined);
  assert.equal((await app.state()).connections.find(c => c.id === second).terminal.font_size, 18);
  assert.equal((await app.state()).connections.find(c => c.id === id).terminal.font_size, 22);
  const currentConfig = parse(await readFile(config, 'utf8'));
  delete currentConfig.profiles.other;
  await writeFile(config, stringify(currentConfig));
  await api('reloadConfig');
  await waitState(s => s.connections.find(c => c.id === second)?.remoteSessions?.sessions.length === 5, 'deleted profile inherits discovery');
  assert.equal((await app.state()).connections.find(c => c.id === second).terminal.font_size, 22);
  await api('disconnect', second);
  await assert.rejects(api('reconnect', second), /Unknown profile/);
  await api('removeConnection', second); await chooseConnection(id); await tab().click();
  await item('scratch').click({ button: 'right' });
  await expect.poll(() => application.evaluate(() => globalThis.rigMenus.at(-1)?.items.at(-1)?.label)).toBe('Kill Session');
  await application.evaluate(() => globalThis.rigMenus.at(-1).items.at(-1).click());
  const modal = await app.modal(); await modal.getByRole('button', { name: 'Kill', exact: true }).click();
  await waitState(s => !s.connections[0].remoteSessions.sessions.some(x => x.label === 'scratch'), 'killed session reconciles');
  assert.throws(() => tmux('has-session', '-t', 'scratch'));
  const retainedHelper = (await app.state()).connections[0].processes.find(p => p.name === 'Bartizan Helper').pid;
  await api('settings', { remoteSessionIntegration: false });
  await waitState(s => !s.connections[0].remoteSessions, 'integration disabled');
  process.kill(retainedHelper, 0);
  assert.equal((await app.state()).connections[0].processes.find(p => p.name === 'Bartizan Helper').pid, retainedHelper);
  await api('settings', { remoteSessionIntegration: true });
  await waitState(s => s.connections[0].remoteSessions && !s.connections[0].remoteSessions.loading, 'integration enabled');
  const draft = await api('profileDraft', 'test');
  await api('profileSave', { token: draft.token, values: { remote_sessions: false }, reset: [], connect: false });
  await waitState(s => !s.connections[0].remoteSessions, 'profile disables integration');
  const inherited = await api('profileDraft', 'test');
  await api('profileSave', { token: inherited.token, values: {}, reset: ['remote_sessions'], connect: false });
  await waitState(s => s.connections[0].remoteSessions?.sessions.length === 4, 'profile inherits integration');
  assert.equal((await app.state()).connections[0].processes.find(p => p.name === 'Bartizan Helper').pid, retainedHelper, 'Integration toggles reuse the helper');
  assert.equal(errors.length, 0, errors.join('\n'));
  const lastStartedHelper = await readFile(pidFile, 'utf8');
  await writeFile(failHelper, '');
  process.kill(retainedHelper, 'SIGKILL');
  await waitState(s => s.connections[0].processes.some(p => p.name === 'Bartizan Helper' && p.status === 'retrying'), 'helper backoff');
  await api('settings', { remoteSessionIntegration: false });
  await waitState(s => !s.connections[0].processes.some(p => p.name === 'Bartizan Helper'), 'backoff cancelled');
  await new Promise(resolve => setTimeout(resolve, 1500));
  assert.equal(await readFile(pidFile, 'utf8'), lastStartedHelper, 'Releasing integration demand cancels restart');
  await unlink(failHelper);
  await api('settings', { remoteSessionIntegration: true });
  await waitState(s => s.connections[0].remoteSessions?.sessions.length === 4, 'integration starts helper after cancelled backoff');
  const finalHelper = (await app.state()).connections[0].processes.find(p => p.name === 'Bartizan Helper').pid;
  await app.close();
  await expect.poll(async () => {
    try { return /State:\s+Z/.test(await readFile(`/proc/${finalHelper}/status`, 'utf8')); }
    catch (error) { if (error.code === 'ENOENT') return true; throw error; }
  }).toBe(true);
  tmux('has-session', '-t', 'build');
  console.log('Socket discovery, explicit commands, message fanout, refresh interaction, helper recovery and session actions passed.');
});
