import assert from 'node:assert/strict';
import { chromium, expect } from '@playwright/test';
import { spawn } from 'node:child_process';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { get } from 'node:http';
import { WebSocket } from 'ws';
import electron from 'electron';
import { withDirectory, startSshd, sshProfile, waitFor } from './lib/harness.mjs';

for (const runtime of ['node', 'electron']) await withDirectory(`web-${runtime}`, async (directory, cleanup) => {
  const executable = runtime === 'node' ? process.execPath : process.env.BARTIZAN_EXECUTABLE ?? electron;
  const prefix = runtime === 'node' ? ['dist/server.cjs'] : [...(process.env.BARTIZAN_EXECUTABLE ? [] : ['.']), 'serve'];
  const sshd = await startSshd(directory);
  cleanup(sshd.stop);
  const config = join(directory, 'config.yaml');
  await writeFile(config, `version: 1\nprofiles:\n  fixture:\n${sshProfile(sshd)}`);
  const refused = spawn(executable, [...prefix, '--host', '0.0.0.0', '--port', '0'], { stdio: ['ignore', 'pipe', 'pipe'] });
  let warning = ''; refused.stderr.on('data', chunk => warning += chunk);
  assert.equal(await new Promise(resolve => refused.on('exit', resolve)), 1);
  assert.match(warning, /NO AUTHENTICATION/);
  assert.match(warning, /--allow-remote/);
  const server = spawn(executable, [...prefix, '--port', '0', '--config', config], { env: { ...process.env, DISPLAY: '', BARTIZAN_DATA_DIR: join(directory, 'state') } });
  let log = ''; server.stdout.on('data', chunk => log += chunk); server.stderr.on('data', chunk => log += chunk);
  cleanup(async () => { if (server.exitCode === null) { const exited = new Promise(resolve => server.once('exit', resolve)); server.kill('SIGTERM'); await exited; } });
  const url = await waitFor(() => /Bartizan listening on (http:\/\/\S+)/.exec(log)?.[1], 'web server');
  assert.equal((await fetch(url + '/server.cjs')).status, 404);
  assert.equal(await new Promise((resolve, reject) => { get(url, { headers: { host: 'attacker.test' } }, response => { response.resume(); resolve(response.statusCode); }).on('error', reject); }), 403);
  const foreign = new WebSocket(url.replace('http:', 'ws:') + '/socket', { origin: 'http://attacker.test' });
  await new Promise(resolve => foreign.on('error', resolve));
  const browser = await chromium.launch({ executablePath: process.env.BARTIZAN_CHROMIUM ?? '/usr/bin/chromium', headless: true, chromiumSandbox: true });
  cleanup(() => browser.close());
  const failedPage = await browser.newPage();
  await failedPage.routeWebSocket('**/socket', socket => socket.close());
  await failedPage.goto(url);
  await expect(failedPage.getByRole('alert')).toHaveText('Connection to Bartizan server closed.');
  await failedPage.close();
  const page = await browser.newPage();
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(url);
  // Connect draws in the page, where there is no overlay, and hands focus back to New Connection as it closes.
  const start = page.getByRole('button', { name: 'New Connection', exact: true });
  await start.click();
  await expect(page.locator('#connect-dialog').getByRole('textbox', { name: 'Profile or Host', exact: true })).toBeFocused();
  await expect(page.locator('#connect-dialog .profile-row[data-id="fixture"]')).toBeVisible();
  await page.locator('#connect-dialog').getByRole('button', { name: 'Close', exact: true }).click();
  await expect(start).toBeFocused();
  const api = (name, ...args) => page.evaluate(({ name, args }) => window.bartizan[name](...args), { name, args });
  assert.deepEqual(await api('capabilities'), { embeddedBrowser: false, nativeFilePicker: false });
  await assert.rejects(api('newBrowser', 'missing'), /Unsupported operation/);
  await page.evaluate(() => { window.rigOutput = ''; window.bartizan.onEvent(event => { if (event.type === 'state') window.rigState = event.state; if (event.type === 'data') window.rigOutput += event.data; }); });
  await page.evaluate(async () => {
    const clipboard = navigator.clipboard;
    Object.defineProperty(navigator, 'clipboard', { configurable: true, value: undefined });
    try { await window.bartizan.copy('Browser clipboard fallback'); }
    finally { Object.defineProperty(navigator, 'clipboard', { configurable: true, value: clipboard }); }
  });
  // Choosing a profile in Connect connects it, and its terminal takes focus.
  await start.click();
  await page.locator('#connect-dialog .profile-row[data-id="fixture"] .profile-item').click();
  await page.waitForFunction(() => window.rigState?.terminals[0]?.status === 'connected');
  const connection = await page.evaluate(() => window.rigState.connections[0].id);
  const terminal = await page.evaluate(() => window.rigState.terminals[0].id);
  await expect(page.locator('.terminal-surface:not([hidden]) .xterm-helper-textarea')).toBeFocused();
  await page.locator(`.connection-chip[data-id="${connection}"] .connection-titles`).click();
  await page.locator(`[data-kind="terminal"][data-id="${terminal}"]`).click();
  await api('input', terminal, "printf 'WEB_%s\\n' READY\n");
  await page.waitForFunction(() => window.rigOutput.includes('WEB_READY'));
  await api('resize', terminal, 91, 37);
  await api('input', terminal, 'stty size\n');
  await page.waitForFunction(() => window.rigOutput.includes('37 91'));
  await expect(page.getByRole('button', { name: 'New Browser Tab', exact: true })).toBeHidden();
  await page.locator('.connection-add').click();
  await page.waitForFunction(() => window.rigState.terminals.length === 2);
  await expect(page.getByRole('menu')).toHaveCount(0);
  await page.locator(`[data-kind="terminal"][data-id="${terminal}"]`).click({ button: 'right' });
  await expect(page.getByRole('menuitem', { name: 'Move Down', exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  const popupEvent = page.waitForEvent('popup');
  await page.evaluate(() => window.bartizan.openLink('', 'https://example.com/'));
  const popup = await popupEvent; await popup.close();
  for (const theme of ['rail', 'tabs', 'console']) {
    await api('settings', { theme });
    await expect(page.locator('html')).toHaveAttribute('data-theme', theme);
    await expect(page.getByRole('button', { name: 'New Browser Tab', exact: true })).toBeHidden();
    const count = await page.evaluate(() => window.rigState.terminals.length);
    await page.locator('.connection-add').click();
    await page.waitForFunction(count => window.rigState.terminals.length === count + 1, count);
    await expect(page.getByRole('menu')).toHaveCount(0);
    await page.locator('.connection-chip').click({ button: 'right' });
    await expect(page.getByRole('menuitem', { name: 'New Terminal', exact: true })).toBeVisible();
    await expect(page.getByRole('menuitem', { name: 'New Browser Session', exact: true })).toHaveCount(0);
    await page.keyboard.press('Escape');
    const backgrounds = {};
    for (const appearance of ['light', 'dark', 'system']) {
      await page.emulateMedia({ colorScheme: appearance === 'light' ? 'dark' : 'light' });
      await api('settings', { appearance });
      const effective = appearance === 'system' ? await page.evaluate(() => matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') : appearance;
      await expect(page.locator('html')).toHaveAttribute('data-appearance', effective);
      backgrounds[appearance] = await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--bg-main'));
      if (appearance === 'dark') assert.notEqual(backgrounds.light, backgrounds.dark, 'Theme colors follow appearance despite the opposite OS preference');
      if (appearance === 'system') assert.equal(backgrounds.system, backgrounds.light);
      await api('reportError', { source: 'rig', message: `Web error ${appearance}` });
      await page.getByText(`Web error ${appearance}`, { exact: true }).last().click();
      await expect(page.locator('#errors-dialog')).toBeVisible();
      await page.locator('#errors-dialog').getByRole('button', { name: 'Close', exact: true }).click();
      await expect(page.locator('#errors-dialog')).toBeHidden();
    }
  }
  assert.equal(browser.contexts().flatMap(context => context.pages()).length, 1, 'Notifications stay in the app page');
  const second = await browser.newPage(); await second.goto(url);
  await second.waitForFunction(() => window.bartizan);
  const firstDraft = await api('profileDraft');
  await second.evaluate(() => window.bartizan.profileDraft());
  const changes = { token: firstDraft.token, values: { host: '127.0.0.1' }, reset: [] };
  assert.ok((await api('profilePreview', changes)).includes('127.0.0.1'), 'Another client cannot expire this profile draft');
  await second.close();
  await api('disconnect', connection);
  await page.waitForFunction(() => window.rigState.connections[0].status === 'closed');
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-appearance', await page.evaluate(() => matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'));
  assert.deepEqual(errors, []);
  console.log(`${runtime}: web terminals, capabilities, direct terminal creation, context menus, external links, settings, error dialogs and independent profile drafts work without a desktop window.`);
});
